### ISSUE TITLE
1.0.4 only do server side rendering

### ISSUE THREAD

**Issue by skanaar** [rendrjs/rendr#476] opened 2015-05-13 11:11 UTC
Upgrading to Rendr 1.0.4 breaks client side rendering of views.

**Steps to reproduce**
1: install Rendr example *00_simple*, with version *1.0.4* and required dependencies (_handlebars, qs2_)
2: load example
3: edit `<body>` background color to _pink_
4: click _Repos_ link

**Expected behaviour**
Repos view loads, background stays pink

**Actual behaviour**
Entire page reloads from server, backgrounds reverts to white

**Comment by bigethan** [comment] 2015-05-13 16:38
Heya @skanaar - there was a recent change to the Rendr code in 1.0.4 and the examples need an update to get their templating working again. @ingiulio (author of the change) should be along shortly to help :-)

**Comment by ingiulio** [comment] 2015-05-13 17:48
Hey @skanaar, could you elaborate more on the step n.3 and how you edit the background color?
I'm trying to get a better understanding of the problem here.
Thank you

**Comment by skanaar** [comment] 2015-05-13 17:58
@ingiulio : I added `background: pink` the style of the `<body>` tag in Chrome DevTools. It doesn't have anything to do directly with the problem, it is just to visualise that the entire page is reloaded from server when following any routes.

**Comment by ingiulio** [comment] 2015-05-13 18:01
@skanaar cool, that's what I tried to reproduce the issue and it seems to be working fine for me.
Can you please try pulling this https://github.com/ingiulio/rendr-examples/tree/addHandlebarsDep and giving it a run? It's the branch I created for the PR that has to go in `rendr-examples` (https://github.com/rendrjs/rendr-examples/pull/20)

**Comment by rickysahu** [comment] 2015-05-15 18:30
@ingiulio Your branch is working as intended. Thanks for updating.

**Comment by saponifi3d** [comment] 2015-05-15 18:30
@skanaar thanks for reporting the issue!  Sorry about that - PR has been merged. hopefully everything is working fine for you now :)

**Closed** 2015-05-15 18:31 UTC
